"""empty message

Revision ID: 0f18e71e5f3d
Revises: c413e72d054a
Create Date: 2024-02-09 10:20:01.570080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f18e71e5f3d'
down_revision = 'c413e72d054a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('skin_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('gender')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
