"""empty message

Revision ID: 261aca6ead43
Revises: cc3634d17cf4
Create Date: 2024-02-12 14:03:42.409315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261aca6ead43'
down_revision = 'cc3634d17cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_constraint('favourite_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favourite_planet_id_fkey', 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###
