"""empty message

Revision ID: 736356322e3b
Revises: e316b62cec07
Create Date: 2024-02-09 11:08:26.038798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736356322e3b'
down_revision = 'e316b62cec07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###
