"""empty message

Revision ID: cc3634d17cf4
Revises: dfa4499519ea
Create Date: 2024-02-09 11:48:27.629620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3634d17cf4'
down_revision = 'dfa4499519ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_img', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('crew', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('crew')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('description')
        batch_op.drop_column('url_img')

    # ### end Alembic commands ###
